name: rdkit_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=py311haa95532_0
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.1=py311haa95532_0
  - contourpy=1.3.3=py311h3fd045d_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=py311haa95532_0
  - et_xmlfile=2.0.0=py311haa95532_0
  - executing=2.2.1=py311haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py311h3f79411_0
  - freetype=2.14.1=h57928b3_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - greenlet=3.2.4=py311h3e6a449_1
  - icu=75.1=he0c23c2_0
  - ipykernel=6.31.0=py311h4442805_0
  - ipython=9.7.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_1
  - jupyter_core=5.8.1=py311haa95532_0
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libboost=1.86.0=h9dfe17d_4
  - libboost-python=1.86.0=py311h05ac4f6_4
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.86.1=hd9c3897_2
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libpq=18.0=h063c6db_0
  - librdkit=2025.09.2=h0cb3073_0
  - libsodium=1.0.20=h83e8143_0
  - libsqlite=3.51.0=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - matplotlib-base=3.10.7=py311h1675fdf_0
  - matplotlib-inline=0.2.1=py311haa95532_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=py311haa95532_0
  - numpy=2.3.4=py311h80b3fa1_0
  - openjpeg=2.5.4=h24db6dd_0
  - openpyxl=3.1.5=py311h827c3e9_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - parso=0.8.5=py311haa95532_0
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py311hf7ee305_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=py311haa95532_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=py311haa95532_0
  - pycairo=1.28.0=py311h109ce6e_1
  - pygments=2.19.2=py311haa95532_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.11.14=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311h885b0b7_0
  - pyzmq=27.1.0=py311h7149c55_1
  - qhull=2020.2=hc790b64_5
  - rdkit=2025.09.2=py311h31bcb41_0
  - reportlab=4.4.4=py311h3485c13_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.44=py311h3485c13_0
  - stack_data=0.6.3=py311haa95532_0
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.1=py311h827c3e9_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py311h3485c13_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.13=py311haa95532_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstd=1.5.7=hbeecb71_2
prefix: C:\Users\20241252\.conda\envs\rdkit_env
